DROP TABLE IF EXISTS FUNCTION_BUNDLE

CREATE TABLE FUNCTION_BUNDLE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    functionBundleId VARCHAR(250) NOT NULL,
    functionId VARCHAR(250) NOT NULL,
    priceByMinute DOUBLE NOT NULL,
    discount DOUBLE,
)
