/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FunctionIdentifier } from './function-identifier';
import { FunctionName } from './function-name';
import { FunctionPricing } from './function-pricing';


export interface DeviceFunctionDto { 
    identifier?: FunctionIdentifier;
    name?: FunctionName;
    pricing?: FunctionPricing;
}

